return {
    {
        fname = "cpp",
        title = "C++",
        desc  = "The C++ code generated by RobCoGen",
        img   = "img/cpp-logo.svg",
    },
    {
        fname = "octave",
        title = "Octave",
        desc  = "The Octave code generated by RobCoGen",
        img   = "img/octave-logo.svg",
    },
}
